#!/bin/bash
#
# Writes Perl.xcconfig describing the perl this machine has, so the perl
# plugin builds against it rather than against a copy carried in the tree.
#
# The headers live inside the SDK rather than on the live filesystem, which
# is why perl reports them with -iwithsysroot. The library is a real file, so
# it is linked by its own path.

set -euo pipefail

OUT="${1:-Perl.xcconfig}"

if ! command -v perl >/dev/null 2>&1; then
    echo "warning: no perl found, the perl plugin will not build" >&2
    printf '// no perl was found when this was generated\nXA_PERL_CORE =\nXA_PERL_LDFLAGS =\n' > "$OUT"
    exit 0
fi

ARCHLIB="$(perl -MConfig -e 'print $Config{archlib}')"
CORE="$ARCHLIB/CORE"
VERSION="$(perl -MConfig -e 'print $Config{version}')"

# $(SDKROOT) is prefixed at build time, so the path stays relative to
# whichever SDK is in use.
SDK_RELATIVE="${CORE#/}"

cat > "$OUT" <<EOF
// Generated by tools/gen_perl_xcconfig.sh. Do not edit.
// perl $VERSION

XA_PERL_CORE = \$(SDKROOT)/$SDK_RELATIVE
XA_PERL_LDFLAGS = -L$CORE -lperl
EOF

echo "perl $VERSION: $CORE"
