#!/bin/bash
#
# Writes Perl.xcconfig describing the perl to build the plugin against, so it
# binds to an interpreter the machine already has rather than one carried in
# the tree.
#
# /usr/bin/perl is preferred over whatever comes first in PATH. A build
# machine may well have a newer perl from Homebrew, but linking against that
# would leave the shipped plugin looking for /opt/homebrew on machines that
# have no such thing. The system perl is the one every user has.
#
# Apple ships the system perl's headers inside the SDK rather than on the
# live filesystem, which is why perl itself reports them with -iwithsysroot.
# Any other perl keeps its headers next to itself. Both are handled.

set -euo pipefail

OUT="${1:-Perl.xcconfig}"

if [ -x /usr/bin/perl ]; then
    PERL=/usr/bin/perl
elif command -v perl >/dev/null 2>&1; then
    PERL="$(command -v perl)"
    echo "note: no /usr/bin/perl, falling back to $PERL" >&2
else
    echo "warning: no perl found, the perl plugin will not build" >&2
    printf '// no perl was found when this was generated\nXA_PERL_CORE =\nXA_PERL_LDFLAGS =\n' > "$OUT"
    exit 0
fi

CORE="$("$PERL" -MConfig -e 'print $Config{archlib}')/CORE"
VERSION="$("$PERL" -MConfig -e 'print $Config{version}')"
SDK="$(xcrun --show-sdk-path 2>/dev/null || true)"

if [ -f "$CORE/EXTERN.h" ]; then
    # Headers are real files, so name them directly.
    HEADERS="$CORE"
elif [ -n "$SDK" ] && [ -f "$SDK/$CORE/EXTERN.h" ]; then
    # Headers only exist inside the SDK, so keep the path relative to it.
    HEADERS="\$(SDKROOT)${CORE}"
else
    echo "error: perl $VERSION headers are neither at $CORE nor inside the SDK" >&2
    exit 1
fi

cat > "$OUT" <<EOF
// Generated by tools/gen_perl_xcconfig.sh. Do not edit.
// perl $VERSION from $PERL

XA_PERL_CORE = $HEADERS
XA_PERL_LDFLAGS = -L$CORE -lperl
EOF

echo "perl $VERSION ($PERL)"
echo "  headers: $HEADERS"
